# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\ContaoFilepondUploader\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Widget}

    markocupic_contao_filepond_uploader.transfer_key:
        class: Markocupic\ContaoFilepondUploader\TransferKey
        public: true
